// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         docId: "docId",
 *         layerName: "layerName",
 *         pageKey: "pageKey"
 *     }
 */
export interface DocPagesSetScaleRequest {
    docId: string;
    layerName: string;
    /** The page's address, `obj:N`: the page's indirect object number, the durable identity every `PageLayout.ref` carries. Mirrors `annotKey` and `fieldKey`. */
    pageKey: string;
    /** Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead. */
    "X-Document-Password"?: string;
    measure: DocPagesSetScaleRequest.Measure | null;
}

export namespace DocPagesSetScaleRequest {
    export interface Measure {
        subtype: Measure.Subtype;
        ratio?: string | undefined;
        x: Measure.X.Item[];
        y?: Measure.Y.Item[] | undefined;
        distance: Measure.Distance.Item[];
        area: Measure.Area.Item[];
        angle?: Measure.Angle.Item[] | undefined;
        slope?: Measure.Slope.Item[] | undefined;
        origin?: Measure.Origin | undefined;
        cyx?: number | undefined;
    }

    export namespace Measure {
        export const Subtype = {
            Rl: "RL",
        } as const;
        export type Subtype = (typeof Subtype)[keyof typeof Subtype];
        export type X = X.Item[];

        export namespace X {
            export interface Item {
                unit: string;
                conversion: number;
                fraction?: Item.Fraction | undefined;
                precision?: number | undefined;
                fixed?: boolean | undefined;
                thousands?: string | undefined;
                decimal?: string | undefined;
                prefixSpacing?: string | undefined;
                suffixSpacing?: string | undefined;
                labelPosition?: Item.LabelPosition | undefined;
            }

            export namespace Item {
                export const Fraction = {
                    Decimal: "decimal",
                    Fraction: "fraction",
                    Round: "round",
                    Truncate: "truncate",
                } as const;
                export type Fraction = (typeof Fraction)[keyof typeof Fraction];
                export const LabelPosition = {
                    Suffix: "suffix",
                    Prefix: "prefix",
                } as const;
                export type LabelPosition = (typeof LabelPosition)[keyof typeof LabelPosition];
            }
        }

        export type Y = Y.Item[];

        export namespace Y {
            export interface Item {
                unit: string;
                conversion: number;
                fraction?: Item.Fraction | undefined;
                precision?: number | undefined;
                fixed?: boolean | undefined;
                thousands?: string | undefined;
                decimal?: string | undefined;
                prefixSpacing?: string | undefined;
                suffixSpacing?: string | undefined;
                labelPosition?: Item.LabelPosition | undefined;
            }

            export namespace Item {
                export const Fraction = {
                    Decimal: "decimal",
                    Fraction: "fraction",
                    Round: "round",
                    Truncate: "truncate",
                } as const;
                export type Fraction = (typeof Fraction)[keyof typeof Fraction];
                export const LabelPosition = {
                    Suffix: "suffix",
                    Prefix: "prefix",
                } as const;
                export type LabelPosition = (typeof LabelPosition)[keyof typeof LabelPosition];
            }
        }

        export type Distance = Distance.Item[];

        export namespace Distance {
            export interface Item {
                unit: string;
                conversion: number;
                fraction?: Item.Fraction | undefined;
                precision?: number | undefined;
                fixed?: boolean | undefined;
                thousands?: string | undefined;
                decimal?: string | undefined;
                prefixSpacing?: string | undefined;
                suffixSpacing?: string | undefined;
                labelPosition?: Item.LabelPosition | undefined;
            }

            export namespace Item {
                export const Fraction = {
                    Decimal: "decimal",
                    Fraction: "fraction",
                    Round: "round",
                    Truncate: "truncate",
                } as const;
                export type Fraction = (typeof Fraction)[keyof typeof Fraction];
                export const LabelPosition = {
                    Suffix: "suffix",
                    Prefix: "prefix",
                } as const;
                export type LabelPosition = (typeof LabelPosition)[keyof typeof LabelPosition];
            }
        }

        export type Area = Area.Item[];

        export namespace Area {
            export interface Item {
                unit: string;
                conversion: number;
                fraction?: Item.Fraction | undefined;
                precision?: number | undefined;
                fixed?: boolean | undefined;
                thousands?: string | undefined;
                decimal?: string | undefined;
                prefixSpacing?: string | undefined;
                suffixSpacing?: string | undefined;
                labelPosition?: Item.LabelPosition | undefined;
            }

            export namespace Item {
                export const Fraction = {
                    Decimal: "decimal",
                    Fraction: "fraction",
                    Round: "round",
                    Truncate: "truncate",
                } as const;
                export type Fraction = (typeof Fraction)[keyof typeof Fraction];
                export const LabelPosition = {
                    Suffix: "suffix",
                    Prefix: "prefix",
                } as const;
                export type LabelPosition = (typeof LabelPosition)[keyof typeof LabelPosition];
            }
        }

        export type Angle = Angle.Item[];

        export namespace Angle {
            export interface Item {
                unit: string;
                conversion: number;
                fraction?: Item.Fraction | undefined;
                precision?: number | undefined;
                fixed?: boolean | undefined;
                thousands?: string | undefined;
                decimal?: string | undefined;
                prefixSpacing?: string | undefined;
                suffixSpacing?: string | undefined;
                labelPosition?: Item.LabelPosition | undefined;
            }

            export namespace Item {
                export const Fraction = {
                    Decimal: "decimal",
                    Fraction: "fraction",
                    Round: "round",
                    Truncate: "truncate",
                } as const;
                export type Fraction = (typeof Fraction)[keyof typeof Fraction];
                export const LabelPosition = {
                    Suffix: "suffix",
                    Prefix: "prefix",
                } as const;
                export type LabelPosition = (typeof LabelPosition)[keyof typeof LabelPosition];
            }
        }

        export type Slope = Slope.Item[];

        export namespace Slope {
            export interface Item {
                unit: string;
                conversion: number;
                fraction?: Item.Fraction | undefined;
                precision?: number | undefined;
                fixed?: boolean | undefined;
                thousands?: string | undefined;
                decimal?: string | undefined;
                prefixSpacing?: string | undefined;
                suffixSpacing?: string | undefined;
                labelPosition?: Item.LabelPosition | undefined;
            }

            export namespace Item {
                export const Fraction = {
                    Decimal: "decimal",
                    Fraction: "fraction",
                    Round: "round",
                    Truncate: "truncate",
                } as const;
                export type Fraction = (typeof Fraction)[keyof typeof Fraction];
                export const LabelPosition = {
                    Suffix: "suffix",
                    Prefix: "prefix",
                } as const;
                export type LabelPosition = (typeof LabelPosition)[keyof typeof LabelPosition];
            }
        }

        export interface Origin {
            x: number;
            y: number;
        }
    }
}
