/** Stage camera/layout capability protocol without reducer/effect/plugin wiring. */
export { StageToken } from './types';
export type {
  BoxQuery,
  FlowMode,
  Gap,
  GridColumns,
  LayoutKind,
  ScrollBehaviorKind,
  GoToOptions,
  RevealAnchor,
  RevealAnchorValue,
  ResponsiveRule,
  RevealOptions,
  RevealZoom,
  StageBox,
  StageScrollToOptions,
  StageSettings,
  StageState,
  StageAction,
  StageViewState,
  StageCapability,
  StageConfig,
  StagePageChangedEvent,
  StageZoomChangedEvent,
  StageCameraChangedEvent,
  StageMotionEndedEvent,
  StageSettingsChangedEvent,
  StageViewportChangedEvent,
  ViewportPoint,
  ViewportRect,
  ZoomToOptions,
  ArrivalAlignment,
  ArrivalAlignValue,
  Scheduler,
  Viewpoint,
  VisiblePage,
} from './types';
export { ZoomMode } from '@embedpdf/core-stage';
export type {
  Align,
  Alignment,
  AlignmentValue,
  AlignValue,
  Camera,
  Size,
  Point,
  Direction,
  PageFrame,
  ScrollMetrics,
  SpreadMode,
  SizingMode,
  ZoomModeValue,
  ZoomSpec,
} from '@embedpdf/core-stage';
