/**
 * Zod-backed engine HTTP wire entrypoint.
 *
 * Cloud transports and server routes import this subpath when they need
 * runtime validation. Local/browser runtime code should use `/runtime`.
 */

export {
  FieldLockSpecSchema,
  SignatureSeedValueSchema,
  SignatureDTOSchema,
  DocumentProtectionSchema,
  PdfRevisionSchema,
  SignatureSnapshotSchema,
  BaseVersionInfoSchema,
  SignatureCompleteResultSchema,
  SignatureCancelResultSchema,
  ChangeAnalysisSchema,
  SignaturePrepareBodySchema,
  SignatureAppearanceBodySchema,
  LayerAnalysisQuerySchema,
  VersionAnalysisQuerySchema,
  analyzeInputFromQuery,
  DocumentVersionSchema,
  DocumentVersionsSchema,
  DigestAlgorithmSchema,
  ModificationLevelSchema,
  SignaturePreparedWireSchema,
  SignatureCompleteBodySchema,
  DocumentVersionRefSchema,
  ByteRangeSchema,
  encodePrepared,
  decodePrepared,
  toBase64,
  fromBase64,
  DocumentMetadataSchema,
  MetadataPatchSchema,
  MetadataUpdateResultSchema,
  CustomMetadataSchema,
  CustomMetadataPatchSchema,
  CustomMetadataUpdateResultSchema,
  AccessRequestSchema,
  AccessResponseSchema,
  EditSessionAccessSchema,
  EditSessionStatusSchema,
  ObjectNumberRangeSchema,
  ObjectNumberReservationRequestSchema,
  ObjectNumberReservationResponseSchema,
  BundleLimitsSchema,
  OpenDocumentResponseSchema,
  DocumentHeadSchema,
  DocumentSecurityStateSchema,
  PdfSaveModeSchema,
  DocumentManifestSchema,
  ManifestPageSchema,
  CachePinsSchema,
  LayerScopesSchema,
  CacheDeltaSchema,
  MutationMetaSchema,
  EngineErrorPayloadSchema,
  AnnotationListSchema,
  PageTextSnapshotSchema,
  PageGeometrySnapshotSchema,
  PageNetworkRenderFormatSchema,
  PageRenderQuerySchema,
  PageRenderAnnotatedQuerySchema,
  AnnotationAppearancesQuerySchema,
  WidgetAppearancesQuerySchema,
  AnnotationAppearanceManifestSchema,
  AnnotationListMutationMetaSchema,
  AnnotationCreateResultSchema,
  AppearanceOutcomeSchema,
  AnnotationUpdateResultSchema,
  AnnotationDeleteResultSchema,
  AnnotationWireComponents,
  AnnotationPositionSchema,
  AnnotationReorderBodySchema,
  AnnotationReorderResultSchema,
  DocumentWireComponents,
  FormMutationMetaSchema,
  FormWireComponents,
  FormSetValueResultSchema,
  FormResetResultSchema,
  FormResetBodySchema,
  FormWidgetUpdateBodySchema,
  FormImportResultSchema,
  FormRepairResultSchema,
  FormFieldCreateResultSchema,
  FormFieldUpdateResultSchema,
  FormFieldDeleteResultSchema,
  FormWidgetDeleteResultSchema,
  FormWidgetLinkResultSchema,
  FormWidgetRestoreResultSchema,
  FormWidgetUpdateResultSchema,
  FormWidgetsReorderBodySchema,
  FormWidgetsReorderResultSchema,
  FormCalculationsReorderBodySchema,
  FormCalculationsReorderResultSchema,
  FieldPositionSchema,
  PageListSnapshotSchema,
  PageLayoutSchema,
  PageBoxesSchema,
  PagePositionSchema,
  PageReorderInputSchema,
  PageReorderResultSchema,
  AnnotationFlattenInputSchema,
  AnnotationFlattenResultSchema,
  AnnotationAppearanceExportInputSchema,
  AnnotationExportSelectionSchema,
  AnnotationsExportRequestSchema,
  AnnotationImportManifestSchema,
  AnnotationImportResultSchema,
  AnnotationImportOptionsSchema,
  NamedPageEntrySchema,
  PageNameInputSchema,
  PageNameResultSchema,
  PageRemoveNameInputSchema,
  PageRotateInputSchema,
  PageRotateResultSchema,
  PageDeleteInputSchema,
  PageDeleteResultSchema,
  PageInsertInputSchema,
  PageInsertBlankInputSchema,
  PageExtractInputSchema,
  PageInsertResultSchema,
  FormEffectSchema,
  FormEffectsResultSchema,
  PageFlattenInputSchema,
  PageFlattenResultSchema,
  RedactionApplyScopeSchema,
  RedactionApplyResultSchema,
  SearchQuerySchema,
  SearchRequestSchema,
  SearchSnippetSchema,
  SearchMatchSchema,
  SearchSliceSchema,
  IdentitySchema,
} from './wire/schemas';
export {
  PdfActionTypeSchema,
  PdfActionNodeSchema,
  PdfActionTargetRefSchema,
  PdfActionTreeSchema,
  PdfFieldActionsSchema,
  PdfPageActionsSchema,
  PdfAnnotationActionsSchema,
  DocumentActionsSnapshotSchema,
  FieldScriptWriteSchema,
  FieldActionsPatchSchema,
  PdfActionWriteSchema,
  WidgetActionsPatchSchema,
  FileWidgetActionsPatchSchema,
  PdfActionWireComponents,
} from './dto/PdfAction.schema';
export type {
  OpenDocumentResponse,
  AccessRequest,
  AccessResponse,
  RenderPolicy,
  DocumentHead,
  DocumentManifest,
  ManifestPage,
  LayerScopes,
  LayerScopePlane,
  CacheDelta,
  MutationMeta,
} from './wire/schemas';
export {
  FormFieldRefSchema,
  FormWidgetSchema,
  ToggleFieldWidgetSchema,
  FormFieldOptionSchema,
  FormFieldDTOSchema,
  FormKindSchema,
  FormSnapshotSchema,
  FormFieldValueSchema,
  FormDataFormatSchema,
  WidgetAppearanceSchema,
  WidgetPlacementSchema,
  FormFieldOptionInputSchema,
  FormFieldDraftSchema,
  FormFieldPatchSchema,
  FormValueEntrySchema,
} from './forms/schema';
export {
  FormSubmissionEntrySchema,
  FormSubmissionRequestSchema,
  FormSubmissionReceiptSchema,
} from './forms/submission';
export { DEFAULT_LAYER_NAME, wirePaths, wireTemplates } from './wire/paths';
// General resource catalog + route-guard helper (server uses this for
// every read endpoint, not just CDN-cacheable ones).
export { checkResourceAccess, DOC_RESOURCES } from './wire/resources';
export type {
  CapabilityRequirement,
  DocResourceDescriptor,
  DocResourceId,
  RouteKind,
} from './wire/resources';

// CDN-shaped surface — coverage enumeration + per-request URL
// application. Scoped under wire/cdn/ so the boundary stays loud (see
// wire/cdn/index.ts for the contract). Re-exported here for ergonomic
// imports from `@embedpdf/engine-core/wire`; consumers wanting the
// narrower import path can use `@embedpdf/engine-core/wire/cdn`
// directly when that entry is published.
export { applyCdnAccess, cdnCoverageForScope, resolveResourceIdForPath } from './wire/cdn';
export type {
  ApplyCdnAccessInput,
  ApplyCdnAccessResult,
  CdnAccessInfoForApply,
  CdnCoverageEntry,
} from './wire/cdn';
export { decodeToken, encodeToken } from './wire/token';
export type { TokenInput, TokenQuery, TokenScalar, TokenSchema } from './wire/token';
export {
  AnnotationAppearancesRenderTokenSchema,
  AnnotationTokenSchema,
  ActionsTokenSchema,
  ContentTokenSchema,
  DocTokenSchema,
  FormTokenSchema,
  LayoutTokenSchema,
  MetadataTokenSchema,
  RenderTokenSchema,
  SearchTokenSchema,
  WidgetAppearancesRenderTokenSchema,
} from './wire/tokenSchemas';
export {
  decodeAnnotationAppearancesRenderToken,
  decodeAnnotationToken,
  decodeAnnotationsAllToken,
  decodeAnnotationsExportToken,
  decodeActionsToken,
  decodeAttachmentsToken,
  decodeContentToken,
  decodeDocToken,
  decodeDownloadToken,
  decodeFormToken,
  decodeLayoutToken,
  decodeMetadataToken,
  decodeRenderToken,
  decodeWidgetAppearancesRenderToken,
  encodeAnnotationAppearancesRenderToken,
  encodeAnnotationToken,
  encodeAnnotationsAllToken,
  encodeAnnotationsExportToken,
  encodeActionsToken,
  encodeAttachmentsToken,
  encodeContentToken,
  encodeDocToken,
  encodeDownloadToken,
  encodeFormToken,
  encodeLayoutToken,
  encodeMetadataToken,
  encodeRenderToken,
  encodeSearchToken,
  encodeWidgetAppearancesRenderToken,
  decodeSearchToken,
  encodeTokenText,
  decodeTokenText,
  SEARCH_RESULT_FORMAT,
  encodeAppearanceModes,
} from './wire/tokens';
export type { DownloadToken, SearchToken } from './wire/tokens';
export { flatten, unflatten } from './wire/flatten';
export type { WireFlat, WireScalar } from './wire/flatten';
export {
  annotationAppearancesImageOptionsToToken,
  annotationAppearancesImageOptionsToWire,
  annotationRenderOptionsFromImageOptions,
  pageRenderOptionsFromImageOptions,
  renderImageOptionsToToken,
  renderImageOptionsToWire,
  widgetAppearancesImageOptionsToToken,
  widgetAppearancesImageOptionsToWire,
} from './wire/renderOptionsCodec';
export type {
  AnnotationRenderVersion,
  RenderVersions,
  WidgetRenderVersion,
} from './wire/renderOptionsCodec';

// Canonical PDF-document geometry schemas (zod). Exported from `wire` only.
export {
  PdfPointSchema,
  PdfRectSchema,
  PdfSizeSchema,
  PdfQuadSchema,
  PdfRotationSchema,
  LinePointsSchema,
  InkListSchema,
  CalloutLineSchema,
  PagePointSchema,
  PageBoxSchema,
  PageQuadSchema,
} from './geometry/schemas';

export {
  AnnotationRefSchema,
  ColorSchema,
  PointSchema,
  RectSchema,
  LineEndingSchema,
  LineEndingsSchema,
  AnnotationBorderStyleSchema,
  DrawnBorderStyleSchema,
  StandardFontSchema,
  TextAlignmentSchema,
  FreeTextIntentSchema,
  FreeTextIntentWriteSchema,
  VerticalAlignmentSchema,
  CaretIntentSchema,
  StrikeoutIntentSchema,
  InkIntentSchema,
  BlendModeSchema,
} from './annotation/base.schema';

export {
  ANNOTATION_KINDS,
  KIND_BY_SUBTYPE,
  AnnotationSchema,
  AnnotationDraftSchema,
  AnnotationPatchSchema,
  annotationPatchSchemaOf,
  PopupDTOSchema,
  PopupDraftSchema,
  PopupPatchSchema,
  HighlightDTOSchema,
  HighlightDraftSchema,
  HighlightPatchSchema,
  UnderlineDTOSchema,
  UnderlineDraftSchema,
  UnderlinePatchSchema,
  SquigglyDTOSchema,
  SquigglyDraftSchema,
  SquigglyPatchSchema,
  StrikeoutDTOSchema,
  StrikeoutDraftSchema,
  StrikeoutPatchSchema,
  CircleDTOSchema,
  CircleDraftSchema,
  CirclePatchSchema,
  SquareDTOSchema,
  SquareDraftSchema,
  SquarePatchSchema,
  PolygonDTOSchema,
  PolygonDraftSchema,
  PolygonPatchSchema,
  PolylineDTOSchema,
  PolylineDraftSchema,
  PolylinePatchSchema,
  LineDTOSchema,
  LineDraftSchema,
  LinePatchSchema,
  LinkDTOSchema,
  LinkDraftSchema,
  LinkPatchSchema,
  PdfDestinationSchema,
  PdfLinkTargetSchema,
  PdfLinkTargetWritableSchema,
  InkDTOSchema,
  InkDraftSchema,
  InkPatchSchema,
  FreeTextDTOSchema,
  FreeTextDraftSchema,
  FreeTextPatchSchema,
  CaretDTOSchema,
  CaretDraftSchema,
  CaretPatchSchema,
  TextDTOSchema,
  TextDraftSchema,
  TextPatchSchema,
  NoteIconSchema,
  StampDTOSchema,
  StampDraftSchema,
  StampPatchSchema,
  StampFitSchema,
  FileAttachmentDTOSchema,
  FileAttachmentDraftSchema,
  FileAttachmentPatchSchema,
  FileAttachmentIconSchema,
  UnsupportedDTOSchema,
  UnsupportedDraftSchema,
  UnsupportedPatchSchema,
} from './annotation/kinds';
export { WidgetDTOSchema, WidgetPatchSchema } from './annotation/kinds/widget';
export { DateInputSchema, IsoDateTimeSchema } from './dto/IsoDateTime.schema';
export {
  AttachmentFileInfoSchema,
  WireAttachmentFileSchema,
  AttachmentSchema,
  AttachmentRefSchema,
} from './dto/Attachment.schema';
export {
  AttachmentListSchema,
  AttachmentMutationMetaSchema,
  AttachmentCreateResultSchema,
  AttachmentDeleteResultSchema,
} from './wire/schemas';
export type { SignaturePreparedWire, SignatureCompleteBody } from './wire/schemas';
export type {
  SignaturePrepareBody,
  SignatureAppearanceBody,
  LayerAnalysisQuery,
  VersionAnalysisQuery,
  DocumentVersion,
  DocumentVersions,
} from './wire/schemas';
export { encodeAnalysisToken, decodeAnalysisToken, type AnalysisToken } from './wire/tokens';
export type { AnnotationsExportToken } from './wire/tokens';
export { analysisQueryString, type AnalysisQueryInput } from './wire/paths';

export * from './dto/Measure.schema';

export { PageScaleResultSchema } from './wire/schemas';
export { PageRefSchema } from './identity/PageRef.schema';
export {
  CHANGE_REQUEST_LIMITS,
  ChangeAnswerSchema,
  ChangeEntryWireSchema,
  ChangeItemSchema,
  ChangeOpWireSchema,
  ChangeRequestSchema,
  ChangeResponseSchema,
  ChangeResultSchema,
  ChangeWireComponents,
} from './wire/changeSchemas';
