/**
 * Build the runtime worker artifacts into `workers/` (a SIBLING of dist, so
 * tsdown's dist clean never wipes them and publint sees them — this script
 * runs BEFORE epdf-build):
 *
 *   - embedpdf-worker.js         self-contained worker: bootstrap +
 *                              engine-services + the Emscripten glue statically
 *                              bundled; only embedpdf.wasm stays external (the
 *                              worker init message says where it lives, or the
 *                              glue finds it as the script's sibling). The
 *                              default delivery: src/worker-files.ts points the
 *                              consumer's bundler at it, which copies it
 *                              verbatim. Self-hosters copy it too.
 *   - embedpdf-worker.source.js  the same bundle as a string module, for the
 *                              blob: delivery (`worker: 'inline'`, and the
 *                              viewer loaded from another origin than the page).
 *   - encoder-worker.js        the image-encoder worker, emitted verbatim from
 *                              src/render/encoder-worker-source.ts so the blob
 *                              and file deliveries can never drift.
 *
 * The engine worker holds no `import.meta`: the glue's own reference becomes
 * `self.location.href` (the same URL in a worker), so a bundler that parses
 * the file instead of copying it finds no asset reference to resolve, and the
 * file runs as a module or a classic script alike.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import esbuild from 'esbuild';

const packageRoot = fileURLToPath(new URL('..', import.meta.url));
const workersDir = path.join(packageRoot, 'workers');

// ── wasm32 version pin ───────────────────────────────────────────────────────
const wasmPath = fileURLToPath(
  import.meta.resolve('@embedpdf/engine-runtime-wasm32/embedpdf.wasm'),
);
fs.mkdirSync(workersDir, { recursive: true });

// Pre-rename outputs: `files` publishes workers/ wholesale, so a stale
// unclean checkout must never ship both worker generations.
for (const legacy of ['pdfium-worker.js', 'pdfium-worker.source.js', 'pdfium-worker.source.d.ts']) {
  fs.rmSync(path.join(workersDir, legacy), { force: true });
}

// ── engine worker: self-contained bundle + string module ────────────────────
await esbuild.build({
  entryPoints: [path.join(packageRoot, 'src', 'worker', 'worker-entry.ts')],
  outfile: path.join(workersDir, 'embedpdf-worker.js'),
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2020',
  minify: true,
  legalComments: 'none',
  // The glue's `new URL('embedpdf.wasm', import.meta.url)` fallback stays, as
  // `self.location.href`: a copied worker with no wasm source configured finds
  // the wasm as its sibling. The bundled-file and blob deliveries always send
  // an explicit wasmUrl instead (see src/wasm-source.ts).
  define: { 'import.meta.url': 'self.location.href' },
});

const workerCode = fs.readFileSync(path.join(workersDir, 'embedpdf-worker.js'), 'utf8');
fs.writeFileSync(
  path.join(workersDir, 'embedpdf-worker.source.js'),
  `// GENERATED by scripts/build-workers.mjs — workers/embedpdf-worker.js as a string.\n` +
    `export default ${JSON.stringify(workerCode)};\n`,
);
fs.writeFileSync(
  path.join(workersDir, 'embedpdf-worker.source.d.ts'),
  `/** workers/embedpdf-worker.js as a string — the inline worker delivery. */\n` +
    `declare const source: string;\nexport default source;\n`,
);

// ── encoder worker: the shared source string, verbatim ──────────────────────
const encoderBundle = await esbuild.build({
  entryPoints: [path.join(packageRoot, 'src', 'render', 'encoder-worker-source.ts')],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2020',
  write: false,
});
const encoderModule = await import(
  `data:text/javascript;base64,${Buffer.from(encoderBundle.outputFiles[0].text).toString('base64')}`
);
fs.writeFileSync(
  path.join(workersDir, 'encoder-worker.js'),
  `// GENERATED by scripts/build-workers.mjs from src/render/encoder-worker-source.ts.\n` +
    encoderModule.encoderWorkerSource.trimStart(),
);

const size = (file) => `${(fs.statSync(path.join(workersDir, file)).size / 1024).toFixed(0)} kB`;
console.log(
  `[build-workers] embedpdf-worker.js ${size('embedpdf-worker.js')}, ` +
    `embedpdf-worker.source.js ${size('embedpdf-worker.source.js')}, ` +
    `encoder-worker.js ${size('encoder-worker.js')}`,
);
