export { AnnotationReader } from './AnnotationReader';
export { AnnotationAppearanceReader } from './AnnotationAppearanceReader';
export { RawAnnotationReader } from './RawAnnotationReader';
export { AnnotationMutator } from './AnnotationMutator';
export { AnnotationFlattener } from './AnnotationFlattener';
export { AnnotationExporter } from './AnnotationExporter';
export { AnnotationImporter } from './AnnotationImporter';
export { AnnotationBatchApplier } from './AnnotationBatchApplier';
export type { BatchCreate, BatchCreateResult } from './AnnotationBatchApplier';
export { computeMutationImpact } from './internal/mutations/computeMutationImpact';
export type { MutationKind, ImpactInputs } from './internal/mutations/computeMutationImpact';
