// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type AnnotationUnderlineRef =
    | CloudPDF.AnnotationUnderlineRef.ObjectNumber
    | CloudPDF.AnnotationUnderlineRef.Nm
    | CloudPDF.AnnotationUnderlineRef.Index;

export namespace AnnotationUnderlineRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: AnnotationUnderlineRefObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace AnnotationUnderlineRefObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: AnnotationUnderlineRefNm.Page;
        nm: string;
    }

    export namespace AnnotationUnderlineRefNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: AnnotationUnderlineRefIndex.Page;
        index: number;
        revision: AnnotationUnderlineRefIndex.Revision;
    }

    export namespace AnnotationUnderlineRefIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
