// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type AnnotationSquigglyRef =
    | CloudPDF.AnnotationSquigglyRef.ObjectNumber
    | CloudPDF.AnnotationSquigglyRef.Nm
    | CloudPDF.AnnotationSquigglyRef.Index;

export namespace AnnotationSquigglyRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: AnnotationSquigglyRefObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace AnnotationSquigglyRefObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: AnnotationSquigglyRefNm.Page;
        nm: string;
    }

    export namespace AnnotationSquigglyRefNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: AnnotationSquigglyRefIndex.Page;
        index: number;
        revision: AnnotationSquigglyRefIndex.Revision;
    }

    export namespace AnnotationSquigglyRefIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
