// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type AnnotationUnsupportedPopup =
    | CloudPDF.AnnotationUnsupportedPopup.ObjectNumber
    | CloudPDF.AnnotationUnsupportedPopup.Nm
    | CloudPDF.AnnotationUnsupportedPopup.Index;

export namespace AnnotationUnsupportedPopup {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: AnnotationUnsupportedPopupObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace AnnotationUnsupportedPopupObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: AnnotationUnsupportedPopupNm.Page;
        nm: string;
    }

    export namespace AnnotationUnsupportedPopupNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: AnnotationUnsupportedPopupIndex.Page;
        index: number;
        revision: AnnotationUnsupportedPopupIndex.Revision;
    }

    export namespace AnnotationUnsupportedPopupIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
