// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type AnnotationSquigglyRef =
    | CloudPDF.AnnotationSquigglyRef.ObjectNumber
    | CloudPDF.AnnotationSquigglyRef.BaseIndex;

export namespace AnnotationSquigglyRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: AnnotationSquigglyRefObjectNumber.Page;
        objectNumber: number;
    }

    export namespace AnnotationSquigglyRefObjectNumber {
        export interface Page {
            kind: Page.Kind;
            objectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface BaseIndex {
        kind: "baseIndex";
        page: AnnotationSquigglyRefBaseIndex.Page;
        baseIndex: number;
    }

    export namespace AnnotationSquigglyRefBaseIndex {
        export interface Page {
            kind: Page.Kind;
            objectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }
}
