// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type AnnotationUnderlinePopup =
    | CloudPDF.AnnotationUnderlinePopup.ObjectNumber
    | CloudPDF.AnnotationUnderlinePopup.Nm
    | CloudPDF.AnnotationUnderlinePopup.Index;

export namespace AnnotationUnderlinePopup {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: AnnotationUnderlinePopupObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace AnnotationUnderlinePopupObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: AnnotationUnderlinePopupNm.Page;
        nm: string;
    }

    export namespace AnnotationUnderlinePopupNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: AnnotationUnderlinePopupIndex.Page;
        index: number;
        revision: AnnotationUnderlinePopupIndex.Revision;
    }

    export namespace AnnotationUnderlinePopupIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
