// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type AnnotationPatchPolygonMeasureUnknown =
    | CloudPDF.AnnotationPatchPolygonMeasureUnknown.Geospatial
    | CloudPDF.AnnotationPatchPolygonMeasureUnknown.Unknown;

export namespace AnnotationPatchPolygonMeasureUnknown {
    export interface Geospatial {
        subtype: "geospatial";
    }

    export interface Unknown {
        subtype: "unknown";
    }
}
