// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type AnnotationPolygonPopup =
    | CloudPDF.AnnotationPolygonPopup.ObjectNumber
    | CloudPDF.AnnotationPolygonPopup.BaseIndex;

export namespace AnnotationPolygonPopup {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: AnnotationPolygonPopupObjectNumber.Page;
        objectNumber: number;
    }

    export namespace AnnotationPolygonPopupObjectNumber {
        export interface Page {
            kind: Page.Kind;
            objectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface BaseIndex {
        kind: "baseIndex";
        page: AnnotationPolygonPopupBaseIndex.Page;
        baseIndex: number;
    }

    export namespace AnnotationPolygonPopupBaseIndex {
        export interface Page {
            kind: Page.Kind;
            objectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }
}
