// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type AnnotationUnderlinePopup =
    | CloudPDF.AnnotationUnderlinePopup.ObjectNumber
    | CloudPDF.AnnotationUnderlinePopup.BaseIndex;

export namespace AnnotationUnderlinePopup {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: AnnotationUnderlinePopupObjectNumber.Page;
        objectNumber: number;
    }

    export namespace AnnotationUnderlinePopupObjectNumber {
        export interface Page {
            kind: Page.Kind;
            objectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface BaseIndex {
        kind: "baseIndex";
        page: AnnotationUnderlinePopupBaseIndex.Page;
        baseIndex: number;
    }

    export namespace AnnotationUnderlinePopupBaseIndex {
        export interface Page {
            kind: Page.Kind;
            objectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }
}
