// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type AnnotationInkRef =
    | CloudPDF.AnnotationInkRef.ObjectNumber
    | CloudPDF.AnnotationInkRef.Nm
    | CloudPDF.AnnotationInkRef.Index;

export namespace AnnotationInkRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: AnnotationInkRefObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace AnnotationInkRefObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: AnnotationInkRefNm.Page;
        nm: string;
    }

    export namespace AnnotationInkRefNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: AnnotationInkRefIndex.Page;
        index: number;
        revision: AnnotationInkRefIndex.Revision;
    }

    export namespace AnnotationInkRefIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
