// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type ChangeOp =
    | CloudPDF.ChangeOp.AnnotationsCreate
    | CloudPDF.ChangeOp.AnnotationsUpdate
    | CloudPDF.ChangeOp.AnnotationsDelete
    | CloudPDF.ChangeOp.AnnotationsReorder
    | CloudPDF.ChangeOp.FormsSetValue
    | CloudPDF.ChangeOp.FormsSetDisplay
    | CloudPDF.ChangeOp.FormsSetAppearanceText
    | CloudPDF.ChangeOp.FormsReset
    | CloudPDF.ChangeOp.FormsCreate
    | CloudPDF.ChangeOp.FormsUpdate
    | CloudPDF.ChangeOp.FormsDelete
    | CloudPDF.ChangeOp.FormsAddWidget
    | CloudPDF.ChangeOp.FormsRemoveWidget
    | CloudPDF.ChangeOp.FormsDeleteWidget
    | CloudPDF.ChangeOp.FormsReorderCalculations
    | CloudPDF.ChangeOp.FormsReorderWidgets
    | CloudPDF.ChangeOp.FormsUpdateWidget
    | CloudPDF.ChangeOp.FormsSetSignatureAppearance
    | CloudPDF.ChangeOp.MetadataUpdate
    | CloudPDF.ChangeOp.MetadataUpdateCustom;

export namespace ChangeOp {
    export interface AnnotationsCreate {
        type: "annotations.create";
        page: CloudPDF.PageRef;
        data: CloudPDF.AnnotationDraft;
        objectNumber?: number | undefined;
        resources?: ChangeOpAnnotationsCreate.Resources | undefined;
    }

    export namespace ChangeOpAnnotationsCreate {
        export interface Resources {
            appearance?: string | undefined;
            file?: string | undefined;
        }
    }

    export interface AnnotationsUpdate {
        type: "annotations.update";
        ref: CloudPDF.AnnotationRef;
        patch: CloudPDF.AnnotationPatch;
        resources?: ChangeOpAnnotationsUpdate.Resources | undefined;
        expect?: CloudPDF.AnnotationPatch | undefined;
    }

    export namespace ChangeOpAnnotationsUpdate {
        export interface Resources {
            appearance?: string | undefined;
            file?: string | undefined;
        }
    }

    export interface AnnotationsDelete {
        type: "annotations.delete";
        ref: CloudPDF.AnnotationRef;
        expect?: CloudPDF.AnnotationPatch | undefined;
    }

    export interface AnnotationsReorder {
        type: "annotations.reorder";
        page: CloudPDF.PageRef;
        refs: CloudPDF.AnnotationRef[];
        position: CloudPDF.AnnotationPosition;
    }

    export interface FormsSetValue {
        type: "forms.setValue";
        field: CloudPDF.FormFieldRef;
        value: CloudPDF.FormFieldValue;
        expect?: CloudPDF.FormFieldValue | undefined;
    }

    export interface FormsSetDisplay {
        type: "forms.setDisplay";
        field: CloudPDF.FormFieldRef;
        display: ChangeOpFormsSetDisplay.Display;
        expect?: ChangeOpFormsSetDisplay.Expect | undefined;
    }

    export namespace ChangeOpFormsSetDisplay {
        export const Display = {
            Visible: "visible",
            Hidden: "hidden",
            NoPrint: "noPrint",
            NoView: "noView",
        } as const;
        export type Display = (typeof Display)[keyof typeof Display];
        export const Expect = {
            Visible: "visible",
            Hidden: "hidden",
            NoPrint: "noPrint",
            NoView: "noView",
        } as const;
        export type Expect = (typeof Expect)[keyof typeof Expect];
    }

    export interface FormsSetAppearanceText {
        type: "forms.setAppearanceText";
        field: CloudPDF.FormFieldRef;
        text: string;
    }

    export interface FormsReset {
        type: "forms.reset";
        fields?: CloudPDF.FormFieldRef[] | undefined;
    }

    export interface FormsCreate {
        type: "forms.create";
        draft: CloudPDF.FormFieldDraft;
        objectNumber?: number | undefined;
        widgetObjectNumbers?: number[] | undefined;
    }

    export interface FormsUpdate {
        type: "forms.update";
        field: CloudPDF.FormFieldRef;
        patch: CloudPDF.FormFieldPatch;
        expect?: CloudPDF.FormFieldPatch | undefined;
    }

    export interface FormsDelete {
        type: "forms.delete";
        field: CloudPDF.FormFieldRef;
        expect?: CloudPDF.FormFieldPatch | undefined;
    }

    export interface FormsAddWidget {
        type: "forms.addWidget";
        field: CloudPDF.FormFieldRef;
        placement: CloudPDF.WidgetPlacement;
        objectNumber?: number | undefined;
        splitObjectNumber?: number | undefined;
    }

    export interface FormsRemoveWidget {
        type: "forms.removeWidget";
        field: CloudPDF.FormFieldRef;
        widget: CloudPDF.AnnotationRef;
    }

    export interface FormsDeleteWidget {
        type: "forms.deleteWidget";
        widget: CloudPDF.AnnotationRef;
        expect?: CloudPDF.WidgetPatch | undefined;
    }

    export interface FormsReorderCalculations {
        type: "forms.reorderCalculations";
        fields: CloudPDF.FormFieldRef[];
        position: CloudPDF.FieldPosition;
    }

    export interface FormsReorderWidgets {
        type: "forms.reorderWidgets";
        page: CloudPDF.PageRef;
        widgets: CloudPDF.AnnotationRef[];
        position: CloudPDF.AnnotationPosition;
    }

    export interface FormsUpdateWidget {
        type: "forms.updateWidget";
        widget: CloudPDF.AnnotationRef;
        patch: CloudPDF.WidgetPatch;
        expect?: CloudPDF.WidgetPatch | undefined;
    }

    export interface FormsSetSignatureAppearance {
        type: "forms.setSignatureAppearance";
        field: CloudPDF.FormFieldRef;
        appearance: ChangeOpFormsSetSignatureAppearance.Appearance;
    }

    export namespace ChangeOpFormsSetSignatureAppearance {
        export interface Appearance {
            pdf: string;
        }
    }

    export interface MetadataUpdate {
        type: "metadata.update";
        patch: CloudPDF.MetadataPatch;
        expect?: CloudPDF.MetadataPatch | undefined;
    }

    export interface MetadataUpdateCustom {
        type: "metadata.updateCustom";
        patch: Record<string, string | null>;
    }
}
