// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.Javascript
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.Goto
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.Uri
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.Named
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.Hide
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.ResetForm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.GotoRemote
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.Launch
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.Rendition
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.SubmitForm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.Thread
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.Sound
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.Movie
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.ImportData
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.SetOcgState
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.Transition
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.Goto3DView
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot.Unknown;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisibleRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
