// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonActionsActivateRootResetFormFieldsItem =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonActionsActivateRootResetFormFieldsItem.Name
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonActionsActivateRootResetFormFieldsItem.ObjectNumber;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonActionsActivateRootResetFormFieldsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
