// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineActionsActivateRootResetFormFieldsItem =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineActionsActivateRootResetFormFieldsItem.Name
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineActionsActivateRootResetFormFieldsItem.ObjectNumber;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineActionsActivateRootResetFormFieldsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
