// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
