// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInkActionsMouseUpRootHideTargetsItem =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInkActionsMouseUpRootHideTargetsItem.Name
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInkActionsMouseUpRootHideTargetsItem.ObjectNumber;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemInkActionsMouseUpRootHideTargetsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
