// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsActivateRootResetFormFieldsItem =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsActivateRootResetFormFieldsItem.Name
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsActivateRootResetFormFieldsItem.ObjectNumber;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsActivateRootResetFormFieldsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
