// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemLineActionsFocusRootHideTargetsItem =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsFocusRootHideTargetsItem.Name
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsFocusRootHideTargetsItem.ObjectNumber;

export namespace DocAnnotationsList200ResponseAnnotationsItemLineActionsFocusRootHideTargetsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
