// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyTo =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyTo.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyTo.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyToObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyToObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyToNm.Page;
        nm: string;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyToNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyToIndex.Page;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonInReplyToIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
