// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsFocusRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
