// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageOpenRootResetFormFieldsItem =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageOpenRootResetFormFieldsItem.Name
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageOpenRootResetFormFieldsItem.ObjectNumber;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageOpenRootResetFormFieldsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
