// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedRef =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedRef.ObjectNumber
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedRef.Nm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedRef.Index;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedRefObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedRefObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedRefNm.Page;
        nm: string;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedRefNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedRefIndex.Page;
        index: number;
        revision: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedRefIndex.Revision;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedRefIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
