// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemHighlightActionsPageInvisibleRootHideTargetsItem =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsPageInvisibleRootHideTargetsItem.Name
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemHighlightActionsPageInvisibleRootHideTargetsItem.ObjectNumber;

export namespace DocAnnotationsList200ResponseAnnotationsItemHighlightActionsPageInvisibleRootHideTargetsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
