// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonActionsActivateRootHideTargetsItem =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonActionsActivateRootHideTargetsItem.Name
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonActionsActivateRootHideTargetsItem.ObjectNumber;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonActionsActivateRootHideTargetsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
