// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.Javascript
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.Goto
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.Uri
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.Named
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.Hide
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.ResetForm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.GotoRemote
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.Launch
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.Rendition
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.SubmitForm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.Thread
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.Sound
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.Movie
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.ImportData
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.SetOcgState
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.Transition
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.Goto3DView
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot.Unknown;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
