// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnterRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
