// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUpRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
