// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsBlurRootGotoDestination =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsBlurRootGotoDestination.Xyz
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsBlurRootGotoDestination.Fit
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsBlurRootGotoDestination.FitH
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsBlurRootGotoDestination.FitV
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsBlurRootGotoDestination.FitR
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsBlurRootGotoDestination.FitB
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsBlurRootGotoDestination.FitBh
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsBlurRootGotoDestination.FitBv;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsBlurRootGotoDestination {
    export interface Xyz {
        kind: "xyz";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
        top?: (number | null) | undefined;
        zoom?: (number | null) | undefined;
    }

    export interface Fit {
        kind: "fit";
        pageObjectNumber: number;
    }

    export interface FitH {
        kind: "fitH";
        pageObjectNumber: number;
        top?: (number | null) | undefined;
    }

    export interface FitV {
        kind: "fitV";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
    }

    export interface FitR {
        kind: "fitR";
        pageObjectNumber: number;
        left: number;
        bottom: number;
        right: number;
        top: number;
    }

    export interface FitB {
        kind: "fitB";
        pageObjectNumber: number;
    }

    export interface FitBh {
        kind: "fitBH";
        pageObjectNumber: number;
        top?: (number | null) | undefined;
    }

    export interface FitBv {
        kind: "fitBV";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
    }
}
