// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemWidgetActionsMouseDownRootResetFormFieldsItem =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsMouseDownRootResetFormFieldsItem.Name
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsMouseDownRootResetFormFieldsItem.ObjectNumber;

export namespace DocAnnotationsList200ResponseAnnotationsItemWidgetActionsMouseDownRootResetFormFieldsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
