// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnterRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
