// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.Javascript
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.Goto
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.Uri
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.Named
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.Hide
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.ResetForm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.GotoRemote
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.Launch
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.Rendition
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.SubmitForm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.Thread
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.Sound
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.Movie
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.ImportData
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.SetOcgState
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.Transition
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.Goto3DView
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot.Unknown;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpenRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
