// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightPopup =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightPopup.ObjectNumber
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightPopup.Nm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightPopup.Index;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightPopup {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightPopupObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightPopupObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightPopupNm.Page;
        nm: string;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightPopupNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightPopupIndex.Page;
        index: number;
        revision: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightPopupIndex.Revision;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightPopupIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
