// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemStampRef =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampRef.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampRef.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampRef.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemStampRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocAnnotationsList200ResponseAnnotationsItemStampRefObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemStampRefObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: DocAnnotationsList200ResponseAnnotationsItemStampRefNm.Page;
        nm: string;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemStampRefNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: DocAnnotationsList200ResponseAnnotationsItemStampRefIndex.Page;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemStampRefIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemStampRefIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
