// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsMouseUpRootHideTargetsItem =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsMouseUpRootHideTargetsItem.Name
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsMouseUpRootHideTargetsItem.ObjectNumber;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsMouseUpRootHideTargetsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
