// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemWidgetActionsActivateRootGotoDestination =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsActivateRootGotoDestination.Xyz
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsActivateRootGotoDestination.Fit
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsActivateRootGotoDestination.FitH
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsActivateRootGotoDestination.FitV
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsActivateRootGotoDestination.FitR
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsActivateRootGotoDestination.FitB
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsActivateRootGotoDestination.FitBh
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsActivateRootGotoDestination.FitBv;

export namespace DocAnnotationsList200ResponseAnnotationsItemWidgetActionsActivateRootGotoDestination {
    export interface Xyz {
        kind: "xyz";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
        top?: (number | null) | undefined;
        zoom?: (number | null) | undefined;
    }

    export interface Fit {
        kind: "fit";
        pageObjectNumber: number;
    }

    export interface FitH {
        kind: "fitH";
        pageObjectNumber: number;
        top?: (number | null) | undefined;
    }

    export interface FitV {
        kind: "fitV";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
    }

    export interface FitR {
        kind: "fitR";
        pageObjectNumber: number;
        left: number;
        bottom: number;
        right: number;
        top: number;
    }

    export interface FitB {
        kind: "fitB";
        pageObjectNumber: number;
    }

    export interface FitBh {
        kind: "fitBH";
        pageObjectNumber: number;
        top?: (number | null) | undefined;
    }

    export interface FitBv {
        kind: "fitBV";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
    }
}
