// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnterRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
