// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRootResetFormFieldsItem =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRootResetFormFieldsItem.Name
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRootResetFormFieldsItem.ObjectNumber;

export namespace DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRootResetFormFieldsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
