// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUpRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
