// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpenRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
