// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageCloseRootHideTargetsItem =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageCloseRootHideTargetsItem.Name
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageCloseRootHideTargetsItem.ObjectNumber;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageCloseRootHideTargetsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
