// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemSquareActionsPageInvisibleRootHideTargetsItem =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsPageInvisibleRootHideTargetsItem.Name
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquareActionsPageInvisibleRootHideTargetsItem.ObjectNumber;

export namespace DocAnnotationsList200ResponseAnnotationsItemSquareActionsPageInvisibleRootHideTargetsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
