// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRootResetFormFieldsItem =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRootResetFormFieldsItem.Name
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRootResetFormFieldsItem.ObjectNumber;

export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRootResetFormFieldsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
