// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisibleRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
