// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemRedactActionsFocusRootHideTargetsItem =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemRedactActionsFocusRootHideTargetsItem.Name
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemRedactActionsFocusRootHideTargetsItem.ObjectNumber;

export namespace DocAnnotationsList200ResponseAnnotationsItemRedactActionsFocusRootHideTargetsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
