// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageCloseRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
