// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemLinePopup =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinePopup.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinePopup.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinePopup.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemLinePopup {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocAnnotationsList200ResponseAnnotationsItemLinePopupObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemLinePopupObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: DocAnnotationsList200ResponseAnnotationsItemLinePopupNm.Page;
        nm: string;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemLinePopupNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: DocAnnotationsList200ResponseAnnotationsItemLinePopupIndex.Page;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemLinePopupIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemLinePopupIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
