// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageInvisibleRootResetFormFieldsItem =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageInvisibleRootResetFormFieldsItem.Name
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageInvisibleRootResetFormFieldsItem.ObjectNumber;

export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageInvisibleRootResetFormFieldsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
