// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocusRootResetFormFieldsItem[] | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
