// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsBlurRootResetFormFieldsItem =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsBlurRootResetFormFieldsItem.Name
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsBlurRootResetFormFieldsItem.ObjectNumber;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsBlurRootResetFormFieldsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
