// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.Javascript
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.Goto
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.Uri
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.Named
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.Hide
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.ResetForm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.GotoRemote
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.Launch
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.Rendition
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.SubmitForm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.Thread
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.Sound
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.Movie
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.ImportData
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.SetOcgState
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.Transition
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.Goto3DView
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot.Unknown;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
