// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemPolygonPopup =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonPopup.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonPopup.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonPopup.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonPopup {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocAnnotationsList200ResponseAnnotationsItemPolygonPopupObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonPopupObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: DocAnnotationsList200ResponseAnnotationsItemPolygonPopupNm.Page;
        nm: string;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonPopupNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: DocAnnotationsList200ResponseAnnotationsItemPolygonPopupIndex.Page;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemPolygonPopupIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonPopupIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
