// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineReplyTo =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineReplyTo.Nm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineReplyTo.Index;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineReplyToObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineReplyToObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineReplyToNm.Page;
        nm: string;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineReplyToNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineReplyToIndex.Page;
        index: number;
        revision: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineReplyToIndex.Revision;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineReplyToIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
