// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpenRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
