// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageInvisibleRootHideTargetsItem =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageInvisibleRootHideTargetsItem.Name
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageInvisibleRootHideTargetsItem.ObjectNumber;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageInvisibleRootHideTargetsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
