// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextInReplyTo =
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextInReplyTo.ObjectNumber
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextInReplyTo.Nm
    | CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextInReplyTo.Index;

export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextInReplyTo {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextInReplyToObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextInReplyToObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextInReplyToNm.Page;
        nm: string;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextInReplyToNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextInReplyToIndex.Page;
        index: number;
        revision: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextInReplyToIndex.Revision;
    }

    export namespace DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextInReplyToIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
