// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivateRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
