// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsCursorEnterRootHideTargetsItem =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsCursorEnterRootHideTargetsItem.Name
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsCursorEnterRootHideTargetsItem.ObjectNumber;

export namespace DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsCursorEnterRootHideTargetsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
