// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemLinkPopup =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkPopup.ObjectNumber
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkPopup.Nm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLinkPopup.Index;

export namespace DocAnnotationsList200ResponseAnnotationsItemLinkPopup {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocAnnotationsList200ResponseAnnotationsItemLinkPopupObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemLinkPopupObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: DocAnnotationsList200ResponseAnnotationsItemLinkPopupNm.Page;
        nm: string;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemLinkPopupNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: DocAnnotationsList200ResponseAnnotationsItemLinkPopupIndex.Page;
        index: number;
        revision: DocAnnotationsList200ResponseAnnotationsItemLinkPopupIndex.Revision;
    }

    export namespace DocAnnotationsList200ResponseAnnotationsItemLinkPopupIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
