// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolylineActionsPageOpenRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
