// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export interface DocAnnotationsListAll200Response {
    pages: DocAnnotationsListAll200Response.Pages.Item[];
    auditHead?: number | undefined;
}

export namespace DocAnnotationsListAll200Response {
    export type Pages = Pages.Item[];

    export namespace Pages {
        export interface Item {
            pageState: Item.PageState;
            annotations: CloudPDF.DocAnnotationsListAll200ResponsePagesItemAnnotationsItem[];
        }

        export namespace Item {
            export interface PageState {
                page: PageState.Page;
                revision: PageState.Revision;
                weakAnnotationState: CloudPDF.DocAnnotationsListAll200ResponsePagesItemPageStateWeakAnnotationState;
            }

            export namespace PageState {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }

                export interface Revision {
                    docSessionId: string;
                    page: Revision.Page;
                    generation: number;
                }

                export namespace Revision {
                    export interface Page {
                        kind: Page.Kind;
                        pageObjectNumber: number;
                    }

                    export namespace Page {
                        export const Kind = {
                            ObjectNumber: "objectNumber",
                        } as const;
                        export type Kind = (typeof Kind)[keyof typeof Kind];
                    }
                }
            }
        }
    }
}
