// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageCloseRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
