// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRootResetFormFieldsItem =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRootResetFormFieldsItem.Name
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRootResetFormFieldsItem.ObjectNumber;

export namespace DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisibleRootResetFormFieldsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
