// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot =
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.Javascript
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.Goto
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.Uri
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.Named
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.Hide
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.ResetForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.GotoRemote
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.GotoEmbedded
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.Launch
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.Rendition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.SubmitForm
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.Thread
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.Sound
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.Movie
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.ImportData
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.SetOcgState
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.Transition
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.Goto3DView
    | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot.Unknown;

export namespace DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields:
            | CloudPDF.DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExitRootResetFormFieldsItem[]
            | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
