// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemTextActionsFormatRoot =
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.Javascript
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.Goto
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.Uri
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.Named
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.Hide
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.ResetForm
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.GotoRemote
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.GotoEmbedded
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.Launch
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.Rendition
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.SubmitForm
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.Thread
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.Sound
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.Movie
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.ImportData
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.SetOcgState
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.Transition
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.Goto3DView
    | CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRoot.Unknown;

export namespace DocFormsGet200ResponseFieldsItemTextActionsFormatRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields: CloudPDF.DocFormsGet200ResponseFieldsItemTextActionsFormatRootResetFormFieldsItem[] | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
