// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsReset200ResponseFieldsItemUnknownRef =
    | CloudPDF.DocFormsReset200ResponseFieldsItemUnknownRef.ObjectNumber
    | CloudPDF.DocFormsReset200ResponseFieldsItemUnknownRef.Fqn;

export namespace DocFormsReset200ResponseFieldsItemUnknownRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }

    export interface Fqn {
        kind: "fqn";
        name: string;
    }
}
