// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsSetValue200ResponseFieldListboxValueEntry =
    | CloudPDF.DocFormsSetValue200ResponseFieldListboxValueEntry.None
    | CloudPDF.DocFormsSetValue200ResponseFieldListboxValueEntry.Scalar
    | CloudPDF.DocFormsSetValue200ResponseFieldListboxValueEntry.Array
    | CloudPDF.DocFormsSetValue200ResponseFieldListboxValueEntry.Unsupported;

export namespace DocFormsSetValue200ResponseFieldListboxValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
