// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsSetValue200ResponseFieldRadioWidgetsItemRef =
    | CloudPDF.DocFormsSetValue200ResponseFieldRadioWidgetsItemRef.ObjectNumber
    | CloudPDF.DocFormsSetValue200ResponseFieldRadioWidgetsItemRef.Nm
    | CloudPDF.DocFormsSetValue200ResponseFieldRadioWidgetsItemRef.Index;

export namespace DocFormsSetValue200ResponseFieldRadioWidgetsItemRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocFormsSetValue200ResponseFieldRadioWidgetsItemRefObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace DocFormsSetValue200ResponseFieldRadioWidgetsItemRefObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: DocFormsSetValue200ResponseFieldRadioWidgetsItemRefNm.Page;
        nm: string;
    }

    export namespace DocFormsSetValue200ResponseFieldRadioWidgetsItemRefNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: DocFormsSetValue200ResponseFieldRadioWidgetsItemRefIndex.Page;
        index: number;
        revision: DocFormsSetValue200ResponseFieldRadioWidgetsItemRefIndex.Revision;
    }

    export namespace DocFormsSetValue200ResponseFieldRadioWidgetsItemRefIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
