// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsReset200ResponseField =
    | CloudPDF.DocFormsReset200ResponseField.Text
    | CloudPDF.DocFormsReset200ResponseField.Checkbox
    | CloudPDF.DocFormsReset200ResponseField.Radio
    | CloudPDF.DocFormsReset200ResponseField.Combobox
    | CloudPDF.DocFormsReset200ResponseField.Listbox
    | CloudPDF.DocFormsReset200ResponseField.Pushbutton
    | CloudPDF.DocFormsReset200ResponseField.Signature
    | CloudPDF.DocFormsReset200ResponseField.Unknown;

export namespace DocFormsReset200ResponseField {
    export interface Text {
        family: "text";
        ref: CloudPDF.DocFormsReset200ResponseFieldTextRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsReset200ResponseFieldText.Origin;
        flags: DocFormsReset200ResponseFieldText.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsReset200ResponseFieldTextValueEntry;
        defaultValueEntry: CloudPDF.DocFormsReset200ResponseFieldTextDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsReset200ResponseFieldText.Widgets.Item[];
        value: string;
        defaultValue: string;
        maxLength: number | null;
        multiline: boolean;
        password: boolean;
        comb: boolean;
    }

    export namespace DocFormsReset200ResponseFieldText {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsReset200ResponseFieldTextWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }

    export interface Checkbox {
        family: "checkbox";
        ref: CloudPDF.DocFormsReset200ResponseFieldCheckboxRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsReset200ResponseFieldCheckbox.Origin;
        flags: DocFormsReset200ResponseFieldCheckbox.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsReset200ResponseFieldCheckboxValueEntry;
        defaultValueEntry: CloudPDF.DocFormsReset200ResponseFieldCheckboxDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsReset200ResponseFieldCheckbox.Widgets.Item[];
        checked: boolean;
        exportValue: string;
    }

    export namespace DocFormsReset200ResponseFieldCheckbox {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsReset200ResponseFieldCheckboxWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
                onState: string;
                exportValue: string;
                checked: boolean;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }

    export interface Radio {
        family: "radio";
        ref: CloudPDF.DocFormsReset200ResponseFieldRadioRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsReset200ResponseFieldRadio.Origin;
        flags: DocFormsReset200ResponseFieldRadio.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsReset200ResponseFieldRadioValueEntry;
        defaultValueEntry: CloudPDF.DocFormsReset200ResponseFieldRadioDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsReset200ResponseFieldRadio.Widgets.Item[];
        value: string;
        radiosInUnison: boolean;
        noToggleToOff: boolean;
    }

    export namespace DocFormsReset200ResponseFieldRadio {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsReset200ResponseFieldRadioWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
                onState: string;
                exportValue: string;
                checked: boolean;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }

    export interface Combobox {
        family: "combobox";
        ref: CloudPDF.DocFormsReset200ResponseFieldComboboxRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsReset200ResponseFieldCombobox.Origin;
        flags: DocFormsReset200ResponseFieldCombobox.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsReset200ResponseFieldComboboxValueEntry;
        defaultValueEntry: CloudPDF.DocFormsReset200ResponseFieldComboboxDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsReset200ResponseFieldCombobox.Widgets.Item[];
        value: string;
        defaultValue: string;
        edit: boolean;
        options: DocFormsReset200ResponseFieldCombobox.Options.Item[];
    }

    export namespace DocFormsReset200ResponseFieldCombobox {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsReset200ResponseFieldComboboxWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }

        export type Options = Options.Item[];

        export namespace Options {
            export interface Item {
                label: string;
                value: string;
                selected: boolean;
            }
        }
    }

    export interface Listbox {
        family: "listbox";
        ref: CloudPDF.DocFormsReset200ResponseFieldListboxRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsReset200ResponseFieldListbox.Origin;
        flags: DocFormsReset200ResponseFieldListbox.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsReset200ResponseFieldListboxValueEntry;
        defaultValueEntry: CloudPDF.DocFormsReset200ResponseFieldListboxDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsReset200ResponseFieldListbox.Widgets.Item[];
        selectedValues: string[];
        multiSelect: boolean;
        options: DocFormsReset200ResponseFieldListbox.Options.Item[];
    }

    export namespace DocFormsReset200ResponseFieldListbox {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsReset200ResponseFieldListboxWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }

        export type Options = Options.Item[];

        export namespace Options {
            export interface Item {
                label: string;
                value: string;
                selected: boolean;
            }
        }
    }

    export interface Pushbutton {
        family: "pushbutton";
        ref: CloudPDF.DocFormsReset200ResponseFieldPushbuttonRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsReset200ResponseFieldPushbutton.Origin;
        flags: DocFormsReset200ResponseFieldPushbutton.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsReset200ResponseFieldPushbuttonValueEntry;
        defaultValueEntry: CloudPDF.DocFormsReset200ResponseFieldPushbuttonDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsReset200ResponseFieldPushbutton.Widgets.Item[];
    }

    export namespace DocFormsReset200ResponseFieldPushbutton {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsReset200ResponseFieldPushbuttonWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }

    export interface Signature {
        family: "signature";
        ref: CloudPDF.DocFormsReset200ResponseFieldSignatureRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsReset200ResponseFieldSignature.Origin;
        flags: DocFormsReset200ResponseFieldSignature.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsReset200ResponseFieldSignatureValueEntry;
        defaultValueEntry: CloudPDF.DocFormsReset200ResponseFieldSignatureDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsReset200ResponseFieldSignature.Widgets.Item[];
    }

    export namespace DocFormsReset200ResponseFieldSignature {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsReset200ResponseFieldSignatureWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }

    export interface Unknown {
        family: "unknown";
        ref: CloudPDF.DocFormsReset200ResponseFieldUnknownRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsReset200ResponseFieldUnknown.Origin;
        flags: DocFormsReset200ResponseFieldUnknown.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsReset200ResponseFieldUnknownValueEntry;
        defaultValueEntry: CloudPDF.DocFormsReset200ResponseFieldUnknownDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsReset200ResponseFieldUnknown.Widgets.Item[];
        rawValue: string;
    }

    export namespace DocFormsReset200ResponseFieldUnknown {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsReset200ResponseFieldUnknownWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }
}
