// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemUnknownActionsFormatRootResetFormFieldsItem =
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownActionsFormatRootResetFormFieldsItem.Name
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownActionsFormatRootResetFormFieldsItem.ObjectNumber;

export namespace DocFormsGet200ResponseFieldsItemUnknownActionsFormatRootResetFormFieldsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
