// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemCheckboxActionsKeystrokeRootResetFormFieldsItem =
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsKeystrokeRootResetFormFieldsItem.Name
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsKeystrokeRootResetFormFieldsItem.ObjectNumber;

export namespace DocFormsGet200ResponseFieldsItemCheckboxActionsKeystrokeRootResetFormFieldsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
