// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot =
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.Javascript
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.Goto
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.Uri
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.Named
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.Hide
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.ResetForm
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.GotoRemote
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.GotoEmbedded
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.Launch
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.Rendition
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.SubmitForm
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.Thread
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.Sound
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.Movie
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.ImportData
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.SetOcgState
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.Transition
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.Goto3DView
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot.Unknown;

export namespace DocFormsGet200ResponseFieldsItemRadioActionsCalculateRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields: CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsCalculateRootResetFormFieldsItem[] | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
