// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsSetValue200ResponseFieldUnknownDefaultValueEntry =
    | CloudPDF.DocFormsSetValue200ResponseFieldUnknownDefaultValueEntry.None
    | CloudPDF.DocFormsSetValue200ResponseFieldUnknownDefaultValueEntry.Scalar
    | CloudPDF.DocFormsSetValue200ResponseFieldUnknownDefaultValueEntry.Array
    | CloudPDF.DocFormsSetValue200ResponseFieldUnknownDefaultValueEntry.Unsupported;

export namespace DocFormsSetValue200ResponseFieldUnknownDefaultValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
