// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemComboboxActionsFormatRootHideTargetsItem =
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRootHideTargetsItem.Name
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRootHideTargetsItem.ObjectNumber;

export namespace DocFormsGet200ResponseFieldsItemComboboxActionsFormatRootHideTargetsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
