// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemComboboxActionsValidateRootGotoDestination =
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsValidateRootGotoDestination.Xyz
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsValidateRootGotoDestination.Fit
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsValidateRootGotoDestination.FitH
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsValidateRootGotoDestination.FitV
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsValidateRootGotoDestination.FitR
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsValidateRootGotoDestination.FitB
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsValidateRootGotoDestination.FitBh
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsValidateRootGotoDestination.FitBv;

export namespace DocFormsGet200ResponseFieldsItemComboboxActionsValidateRootGotoDestination {
    export interface Xyz {
        kind: "xyz";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
        top?: (number | null) | undefined;
        zoom?: (number | null) | undefined;
    }

    export interface Fit {
        kind: "fit";
        pageObjectNumber: number;
    }

    export interface FitH {
        kind: "fitH";
        pageObjectNumber: number;
        top?: (number | null) | undefined;
    }

    export interface FitV {
        kind: "fitV";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
    }

    export interface FitR {
        kind: "fitR";
        pageObjectNumber: number;
        left: number;
        bottom: number;
        right: number;
        top: number;
    }

    export interface FitB {
        kind: "fitB";
        pageObjectNumber: number;
    }

    export interface FitBh {
        kind: "fitBH";
        pageObjectNumber: number;
        top?: (number | null) | undefined;
    }

    export interface FitBv {
        kind: "fitBV";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
    }
}
