// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsImportData200ResponseFormFieldsItem =
    | CloudPDF.DocFormsImportData200ResponseFormFieldsItem.Text
    | CloudPDF.DocFormsImportData200ResponseFormFieldsItem.Checkbox
    | CloudPDF.DocFormsImportData200ResponseFormFieldsItem.Radio
    | CloudPDF.DocFormsImportData200ResponseFormFieldsItem.Combobox
    | CloudPDF.DocFormsImportData200ResponseFormFieldsItem.Listbox
    | CloudPDF.DocFormsImportData200ResponseFormFieldsItem.Pushbutton
    | CloudPDF.DocFormsImportData200ResponseFormFieldsItem.Signature
    | CloudPDF.DocFormsImportData200ResponseFormFieldsItem.Unknown;

export namespace DocFormsImportData200ResponseFormFieldsItem {
    export interface Text {
        family: "text";
        ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemTextRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsImportData200ResponseFormFieldsItemText.Origin;
        flags: DocFormsImportData200ResponseFormFieldsItemText.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemTextValueEntry;
        defaultValueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemTextDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsImportData200ResponseFormFieldsItemText.Widgets.Item[];
        value: string;
        defaultValue: string;
        maxLength: number | null;
        multiline: boolean;
        password: boolean;
        comb: boolean;
    }

    export namespace DocFormsImportData200ResponseFormFieldsItemText {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemTextWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }

    export interface Checkbox {
        family: "checkbox";
        ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemCheckboxRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsImportData200ResponseFormFieldsItemCheckbox.Origin;
        flags: DocFormsImportData200ResponseFormFieldsItemCheckbox.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemCheckboxValueEntry;
        defaultValueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemCheckboxDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsImportData200ResponseFormFieldsItemCheckbox.Widgets.Item[];
        checked: boolean;
        exportValue: string;
    }

    export namespace DocFormsImportData200ResponseFormFieldsItemCheckbox {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemCheckboxWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
                onState: string;
                exportValue: string;
                checked: boolean;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }

    export interface Radio {
        family: "radio";
        ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemRadioRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsImportData200ResponseFormFieldsItemRadio.Origin;
        flags: DocFormsImportData200ResponseFormFieldsItemRadio.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemRadioValueEntry;
        defaultValueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemRadioDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsImportData200ResponseFormFieldsItemRadio.Widgets.Item[];
        value: string;
        radiosInUnison: boolean;
        noToggleToOff: boolean;
    }

    export namespace DocFormsImportData200ResponseFormFieldsItemRadio {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemRadioWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
                onState: string;
                exportValue: string;
                checked: boolean;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }

    export interface Combobox {
        family: "combobox";
        ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemComboboxRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsImportData200ResponseFormFieldsItemCombobox.Origin;
        flags: DocFormsImportData200ResponseFormFieldsItemCombobox.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemComboboxValueEntry;
        defaultValueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemComboboxDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsImportData200ResponseFormFieldsItemCombobox.Widgets.Item[];
        value: string;
        defaultValue: string;
        edit: boolean;
        options: DocFormsImportData200ResponseFormFieldsItemCombobox.Options.Item[];
    }

    export namespace DocFormsImportData200ResponseFormFieldsItemCombobox {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemComboboxWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }

        export type Options = Options.Item[];

        export namespace Options {
            export interface Item {
                label: string;
                value: string;
                selected: boolean;
            }
        }
    }

    export interface Listbox {
        family: "listbox";
        ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemListboxRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsImportData200ResponseFormFieldsItemListbox.Origin;
        flags: DocFormsImportData200ResponseFormFieldsItemListbox.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemListboxValueEntry;
        defaultValueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemListboxDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsImportData200ResponseFormFieldsItemListbox.Widgets.Item[];
        selectedValues: string[];
        multiSelect: boolean;
        options: DocFormsImportData200ResponseFormFieldsItemListbox.Options.Item[];
    }

    export namespace DocFormsImportData200ResponseFormFieldsItemListbox {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemListboxWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }

        export type Options = Options.Item[];

        export namespace Options {
            export interface Item {
                label: string;
                value: string;
                selected: boolean;
            }
        }
    }

    export interface Pushbutton {
        family: "pushbutton";
        ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemPushbuttonRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsImportData200ResponseFormFieldsItemPushbutton.Origin;
        flags: DocFormsImportData200ResponseFormFieldsItemPushbutton.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemPushbuttonValueEntry;
        defaultValueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemPushbuttonDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsImportData200ResponseFormFieldsItemPushbutton.Widgets.Item[];
    }

    export namespace DocFormsImportData200ResponseFormFieldsItemPushbutton {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemPushbuttonWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }

    export interface Signature {
        family: "signature";
        ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemSignatureRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsImportData200ResponseFormFieldsItemSignature.Origin;
        flags: DocFormsImportData200ResponseFormFieldsItemSignature.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemSignatureValueEntry;
        defaultValueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemSignatureDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsImportData200ResponseFormFieldsItemSignature.Widgets.Item[];
    }

    export namespace DocFormsImportData200ResponseFormFieldsItemSignature {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemSignatureWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }

    export interface Unknown {
        family: "unknown";
        ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemUnknownRef;
        fieldObjectNumber: number;
        name: string;
        origin: DocFormsImportData200ResponseFormFieldsItemUnknown.Origin;
        flags: DocFormsImportData200ResponseFormFieldsItemUnknown.Flags;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemUnknownValueEntry;
        defaultValueEntry: CloudPDF.DocFormsImportData200ResponseFormFieldsItemUnknownDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: DocFormsImportData200ResponseFormFieldsItemUnknown.Widgets.Item[];
        rawValue: string;
    }

    export namespace DocFormsImportData200ResponseFormFieldsItemUnknown {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];

        export interface Flags {
            readOnly: boolean;
            required: boolean;
            noExport: boolean;
            raw: number;
        }

        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.DocFormsImportData200ResponseFormFieldsItemUnknownWidgetsItemRef | null;
                annotObjectNumber: number;
                page: Item.Page | null;
            }

            export namespace Item {
                export interface Page {
                    kind: Page.Kind;
                    pageObjectNumber: number;
                }

                export namespace Page {
                    export const Kind = {
                        ObjectNumber: "objectNumber",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }
}
