// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsSetValue200ResponseFieldPushbuttonValueEntry =
    | CloudPDF.DocFormsSetValue200ResponseFieldPushbuttonValueEntry.None
    | CloudPDF.DocFormsSetValue200ResponseFieldPushbuttonValueEntry.Scalar
    | CloudPDF.DocFormsSetValue200ResponseFieldPushbuttonValueEntry.Array
    | CloudPDF.DocFormsSetValue200ResponseFieldPushbuttonValueEntry.Unsupported;

export namespace DocFormsSetValue200ResponseFieldPushbuttonValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
