// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRef =
    | CloudPDF.DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRef.ObjectNumber
    | CloudPDF.DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRef.BaseIndex;

export namespace DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRefObjectNumber.Page;
        objectNumber: number;
    }

    export namespace DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRefObjectNumber {
        export interface Page {
            kind: Page.Kind;
            objectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface BaseIndex {
        kind: "baseIndex";
        page: DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRefBaseIndex.Page;
        baseIndex: number;
    }

    export namespace DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRefBaseIndex {
        export interface Page {
            kind: Page.Kind;
            objectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }
}
