// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot =
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.Javascript
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.Goto
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.Uri
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.Named
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.Hide
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.ResetForm
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.GotoRemote
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.GotoEmbedded
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.Launch
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.Rendition
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.SubmitForm
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.Thread
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.Sound
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.Movie
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.ImportData
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.SetOcgState
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.Transition
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.Goto3DView
    | CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot.Unknown;

export namespace DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields: CloudPDF.DocFormsGet200ResponseFieldsItemCheckboxActionsCalculateRootResetFormFieldsItem[] | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
