// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot =
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.Javascript
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.Goto
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.Uri
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.Named
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.Hide
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.ResetForm
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.GotoRemote
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.GotoEmbedded
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.Launch
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.Rendition
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.SubmitForm
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.Thread
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.Sound
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.Movie
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.ImportData
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.SetOcgState
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.Transition
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.Goto3DView
    | CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot.Unknown;

export namespace DocFormsGet200ResponseFieldsItemComboboxActionsFormatRoot {
    export interface Javascript {
        type: "javascript";
        subtype: string;
        next: unknown[];
        script: string;
    }

    export interface Goto {
        type: "goto";
        subtype: string;
        next: unknown[];
        destination: CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRootGotoDestination;
    }

    export interface Uri {
        type: "uri";
        subtype: string;
        next: unknown[];
        uri: string;
        isMap: boolean;
    }

    export interface Named {
        type: "named";
        subtype: string;
        next: unknown[];
        name: string;
    }

    export interface Hide {
        type: "hide";
        subtype: string;
        next: unknown[];
        targets: CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRootHideTargetsItem[];
        hide: boolean;
    }

    export interface ResetForm {
        type: "reset-form";
        subtype: string;
        next: unknown[];
        fields: CloudPDF.DocFormsGet200ResponseFieldsItemComboboxActionsFormatRootResetFormFieldsItem[] | null;
        exclude: boolean;
    }

    export interface GotoRemote {
        type: "goto-remote";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface GotoEmbedded {
        type: "goto-embedded";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Launch {
        type: "launch";
        subtype: string;
        next: unknown[];
        filePath: string;
    }

    export interface Rendition {
        type: "rendition";
        subtype: string;
        next: unknown[];
        script?: string | undefined;
    }

    export interface SubmitForm {
        type: "submit-form";
        subtype: string;
        next: unknown[];
    }

    export interface Thread {
        type: "thread";
        subtype: string;
        next: unknown[];
    }

    export interface Sound {
        type: "sound";
        subtype: string;
        next: unknown[];
    }

    export interface Movie {
        type: "movie";
        subtype: string;
        next: unknown[];
    }

    export interface ImportData {
        type: "import-data";
        subtype: string;
        next: unknown[];
    }

    export interface SetOcgState {
        type: "set-ocg-state";
        subtype: string;
        next: unknown[];
    }

    export interface Transition {
        type: "transition";
        subtype: string;
        next: unknown[];
    }

    export interface Goto3DView {
        type: "goto-3d-view";
        subtype: string;
        next: unknown[];
    }

    export interface Unknown {
        type: "unknown";
        subtype: string;
        next: unknown[];
    }
}
