// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemUnknownActionsKeystrokeRootHideTargetsItem =
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownActionsKeystrokeRootHideTargetsItem.Name
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownActionsKeystrokeRootHideTargetsItem.ObjectNumber;

export namespace DocFormsGet200ResponseFieldsItemUnknownActionsKeystrokeRootHideTargetsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
