// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemRadioActionsValidateRootHideTargetsItem =
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsValidateRootHideTargetsItem.Name
    | CloudPDF.DocFormsGet200ResponseFieldsItemRadioActionsValidateRootHideTargetsItem.ObjectNumber;

export namespace DocFormsGet200ResponseFieldsItemRadioActionsValidateRootHideTargetsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
