// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemUnknownActionsValidateRootGotoDestination =
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownActionsValidateRootGotoDestination.Xyz
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownActionsValidateRootGotoDestination.Fit
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownActionsValidateRootGotoDestination.FitH
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownActionsValidateRootGotoDestination.FitV
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownActionsValidateRootGotoDestination.FitR
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownActionsValidateRootGotoDestination.FitB
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownActionsValidateRootGotoDestination.FitBh
    | CloudPDF.DocFormsGet200ResponseFieldsItemUnknownActionsValidateRootGotoDestination.FitBv;

export namespace DocFormsGet200ResponseFieldsItemUnknownActionsValidateRootGotoDestination {
    export interface Xyz {
        kind: "xyz";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
        top?: (number | null) | undefined;
        zoom?: (number | null) | undefined;
    }

    export interface Fit {
        kind: "fit";
        pageObjectNumber: number;
    }

    export interface FitH {
        kind: "fitH";
        pageObjectNumber: number;
        top?: (number | null) | undefined;
    }

    export interface FitV {
        kind: "fitV";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
    }

    export interface FitR {
        kind: "fitR";
        pageObjectNumber: number;
        left: number;
        bottom: number;
        right: number;
        top: number;
    }

    export interface FitB {
        kind: "fitB";
        pageObjectNumber: number;
    }

    export interface FitBh {
        kind: "fitBH";
        pageObjectNumber: number;
        top?: (number | null) | undefined;
    }

    export interface FitBv {
        kind: "fitBV";
        pageObjectNumber: number;
        left?: (number | null) | undefined;
    }
}
