// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsReset200ResponseFieldsItemSignatureWidgetsItemRef =
    | CloudPDF.DocFormsReset200ResponseFieldsItemSignatureWidgetsItemRef.ObjectNumber
    | CloudPDF.DocFormsReset200ResponseFieldsItemSignatureWidgetsItemRef.BaseIndex;

export namespace DocFormsReset200ResponseFieldsItemSignatureWidgetsItemRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocFormsReset200ResponseFieldsItemSignatureWidgetsItemRefObjectNumber.Page;
        objectNumber: number;
    }

    export namespace DocFormsReset200ResponseFieldsItemSignatureWidgetsItemRefObjectNumber {
        export interface Page {
            kind: Page.Kind;
            objectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface BaseIndex {
        kind: "baseIndex";
        page: DocFormsReset200ResponseFieldsItemSignatureWidgetsItemRefBaseIndex.Page;
        baseIndex: number;
    }

    export namespace DocFormsReset200ResponseFieldsItemSignatureWidgetsItemRefBaseIndex {
        export interface Page {
            kind: Page.Kind;
            objectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }
}
