// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsList200ResponseFieldsItemListboxWidgetsItemRef =
    | CloudPDF.DocFormsList200ResponseFieldsItemListboxWidgetsItemRef.ObjectNumber
    | CloudPDF.DocFormsList200ResponseFieldsItemListboxWidgetsItemRef.Nm
    | CloudPDF.DocFormsList200ResponseFieldsItemListboxWidgetsItemRef.Index;

export namespace DocFormsList200ResponseFieldsItemListboxWidgetsItemRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocFormsList200ResponseFieldsItemListboxWidgetsItemRefObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace DocFormsList200ResponseFieldsItemListboxWidgetsItemRefObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: DocFormsList200ResponseFieldsItemListboxWidgetsItemRefNm.Page;
        nm: string;
    }

    export namespace DocFormsList200ResponseFieldsItemListboxWidgetsItemRefNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: DocFormsList200ResponseFieldsItemListboxWidgetsItemRefIndex.Page;
        index: number;
        revision: DocFormsList200ResponseFieldsItemListboxWidgetsItemRefIndex.Revision;
    }

    export namespace DocFormsList200ResponseFieldsItemListboxWidgetsItemRefIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
