// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsList200ResponseFieldsItemCheckboxDefaultValueEntry =
    | CloudPDF.DocFormsList200ResponseFieldsItemCheckboxDefaultValueEntry.None
    | CloudPDF.DocFormsList200ResponseFieldsItemCheckboxDefaultValueEntry.Scalar
    | CloudPDF.DocFormsList200ResponseFieldsItemCheckboxDefaultValueEntry.Array
    | CloudPDF.DocFormsList200ResponseFieldsItemCheckboxDefaultValueEntry.Unsupported;

export namespace DocFormsList200ResponseFieldsItemCheckboxDefaultValueEntry {
    export interface None {
        kind: "none";
    }

    export interface Scalar {
        kind: "scalar";
        value: string;
    }

    export interface Array {
        kind: "array";
        values: string[];
    }

    export interface Unsupported {
        kind: "unsupported";
    }
}
