// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRef =
    | CloudPDF.DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRef.ObjectNumber
    | CloudPDF.DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRef.Nm
    | CloudPDF.DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRef.Index;

export namespace DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRefObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRefObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRefNm.Page;
        nm: string;
    }

    export namespace DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRefNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRefIndex.Page;
        index: number;
        revision: DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRefIndex.Revision;
    }

    export namespace DocFormsList200ResponseFieldsItemPushbuttonWidgetsItemRefIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
