// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsGet200ResponseFieldsItemPushbuttonActionsValidateRootResetFormFieldsItem =
    | CloudPDF.DocFormsGet200ResponseFieldsItemPushbuttonActionsValidateRootResetFormFieldsItem.Name
    | CloudPDF.DocFormsGet200ResponseFieldsItemPushbuttonActionsValidateRootResetFormFieldsItem.ObjectNumber;

export namespace DocFormsGet200ResponseFieldsItemPushbuttonActionsValidateRootResetFormFieldsItem {
    export interface Name {
        kind: "name";
        name: string;
    }

    export interface ObjectNumber {
        kind: "objectNumber";
        objectNumber: number;
    }
}
