// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export interface DocFormsImportData200Response {
    form: DocFormsImportData200Response.Form;
    applied: number;
    skipped: number;
    meta: CloudPDF.MutationMeta;
}

export namespace DocFormsImportData200Response {
    export interface Form {
        formKind: Form.FormKind;
        needsAppearances: boolean;
        fields: CloudPDF.FormField[];
        calculationOrder: (CloudPDF.FormFieldRef | null)[];
    }

    export namespace Form {
        export const FormKind = {
            None: "none",
            Acroform: "acroform",
            Xfa: "xfa",
        } as const;
        export type FormKind = (typeof FormKind)[keyof typeof FormKind];
    }
}
