// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocFormsReset200ResponseFieldPushbuttonWidgetsItemRef =
    | CloudPDF.DocFormsReset200ResponseFieldPushbuttonWidgetsItemRef.ObjectNumber
    | CloudPDF.DocFormsReset200ResponseFieldPushbuttonWidgetsItemRef.Nm
    | CloudPDF.DocFormsReset200ResponseFieldPushbuttonWidgetsItemRef.Index;

export namespace DocFormsReset200ResponseFieldPushbuttonWidgetsItemRef {
    export interface ObjectNumber {
        kind: "objectNumber";
        page: DocFormsReset200ResponseFieldPushbuttonWidgetsItemRefObjectNumber.Page;
        annotObjectNumber: number;
    }

    export namespace DocFormsReset200ResponseFieldPushbuttonWidgetsItemRefObjectNumber {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Nm {
        kind: "nm";
        page: DocFormsReset200ResponseFieldPushbuttonWidgetsItemRefNm.Page;
        nm: string;
    }

    export namespace DocFormsReset200ResponseFieldPushbuttonWidgetsItemRefNm {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Index {
        kind: "index";
        page: DocFormsReset200ResponseFieldPushbuttonWidgetsItemRefIndex.Page;
        index: number;
        revision: DocFormsReset200ResponseFieldPushbuttonWidgetsItemRefIndex.Revision;
    }

    export namespace DocFormsReset200ResponseFieldPushbuttonWidgetsItemRefIndex {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }

        export interface Revision {
            docSessionId: string;
            page: Revision.Page;
            generation: number;
        }

        export namespace Revision {
            export interface Page {
                kind: Page.Kind;
                pageObjectNumber: number;
            }

            export namespace Page {
                export const Kind = {
                    ObjectNumber: "objectNumber",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }
    }
}
