// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocPagesDelete200ResponseLayoutNamedPagesItemTarget =
    | CloudPDF.DocPagesDelete200ResponseLayoutNamedPagesItemTarget.Page
    | CloudPDF.DocPagesDelete200ResponseLayoutNamedPagesItemTarget.Template
    | CloudPDF.DocPagesDelete200ResponseLayoutNamedPagesItemTarget.Dangling;

export namespace DocPagesDelete200ResponseLayoutNamedPagesItemTarget {
    export interface Page {
        kind: "page";
        page: CloudPDF.PageRef;
    }

    export interface Template {
        kind: "template";
        objectNumber: number;
    }

    export interface Dangling {
        kind: "dangling";
    }
}
