// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type DocPagesInsertBlank200ResponseLayoutNamedPagesItemTarget =
    | CloudPDF.DocPagesInsertBlank200ResponseLayoutNamedPagesItemTarget.Page
    | CloudPDF.DocPagesInsertBlank200ResponseLayoutNamedPagesItemTarget.Template
    | CloudPDF.DocPagesInsertBlank200ResponseLayoutNamedPagesItemTarget.Dangling;

export namespace DocPagesInsertBlank200ResponseLayoutNamedPagesItemTarget {
    export interface Page {
        kind: "page";
        page: DocPagesInsertBlank200ResponseLayoutNamedPagesItemTargetPage.Page;
    }

    export namespace DocPagesInsertBlank200ResponseLayoutNamedPagesItemTargetPage {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Template {
        kind: "template";
        objectNumber: number;
    }

    export interface Dangling {
        kind: "dangling";
    }
}
