// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export interface DocPagesViewports200Response {
    viewports: DocPagesViewports200Response.Viewports.Item[];
}

export namespace DocPagesViewports200Response {
    export type Viewports = Viewports.Item[];

    export namespace Viewports {
        export interface Item {
            bbox: Item.Bbox;
            name: string | null;
            measure: CloudPDF.DocPagesViewports200ResponseViewportsItemMeasure | null;
            owned: boolean;
        }

        export namespace Item {
            export interface Bbox {
                x: number;
                y: number;
                width: number;
                height: number;
            }
        }
    }
}
