// This file was auto-generated by Fern from our API Definition.

export interface DocVersionsAnalysis200Response {
    mode: DocVersionsAnalysis200Response.Mode;
    policyVersion: number;
    basis: DocVersionsAnalysis200Response.Basis;
    since: DocVersionsAnalysis200Response.Since;
    until: DocVersionsAnalysis200Response.Until;
    steps: unknown[];
    verdict: DocVersionsAnalysis200Response.Verdict;
}

export namespace DocVersionsAnalysis200Response {
    export const Mode = {
        Authoritative: "authoritative",
        Exploratory: "exploratory",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];

    export interface Basis {
        version: Basis.Version;
        editsVersion: number;
        source: Basis.Source;
    }

    export namespace Basis {
        export interface Version {
            sha256: string;
            byteLength: number;
        }

        export const Source = {
            Persisted: "persisted",
            WorkingCopy: "working-copy",
        } as const;
        export type Source = (typeof Source)[keyof typeof Source];
    }

    export interface Since {
        revisionIndex: number;
        signatureIndex: number | null;
    }

    export interface Until {
        revisionIndex: number;
    }

    export const Verdict = {
        Unchanged: "unchanged",
        Permitted: "permitted",
        Forbidden: "forbidden",
        Indeterminate: "indeterminate",
    } as const;
    export type Verdict = (typeof Verdict)[keyof typeof Verdict];
}
