// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type FormField =
    | CloudPDF.FormField.Text
    | CloudPDF.FormField.Checkbox
    | CloudPDF.FormField.Radio
    | CloudPDF.FormField.Combobox
    | CloudPDF.FormField.Listbox
    | CloudPDF.FormField.Pushbutton
    | CloudPDF.FormField.Signature
    | CloudPDF.FormField.Unknown;

export namespace FormField {
    export interface Text {
        family: "text";
        ref: CloudPDF.FormFieldRef;
        name: string;
        origin: FormFieldText.Origin;
        readOnly: boolean;
        required: boolean;
        noExport: boolean;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.FormFieldTextValueEntry;
        defaultValueEntry: CloudPDF.FormFieldTextDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: FormFieldText.Widgets.Item[];
        value: string;
        defaultValue: string;
        maxLength: number | null;
        multiline: boolean;
        password: boolean;
        comb: boolean;
    }

    export namespace FormFieldText {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];
        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.AnnotationRef | null;
                objectNumber: number;
                page: CloudPDF.PageRef | null;
                rect: Item.Rect | null;
            }

            export namespace Item {
                export interface Rect {
                    x: number;
                    y: number;
                    width: number;
                    height: number;
                }
            }
        }
    }

    export interface Checkbox {
        family: "checkbox";
        ref: CloudPDF.FormFieldRef;
        name: string;
        origin: FormFieldCheckbox.Origin;
        readOnly: boolean;
        required: boolean;
        noExport: boolean;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.FormFieldCheckboxValueEntry;
        defaultValueEntry: CloudPDF.FormFieldCheckboxDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: FormFieldCheckbox.Widgets.Item[];
        checked: boolean;
        exportValue: string;
    }

    export namespace FormFieldCheckbox {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];
        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.AnnotationRef | null;
                objectNumber: number;
                page: CloudPDF.PageRef | null;
                rect: Item.Rect | null;
                onState: string;
                exportValue: string;
                checked: boolean;
            }

            export namespace Item {
                export interface Rect {
                    x: number;
                    y: number;
                    width: number;
                    height: number;
                }
            }
        }
    }

    export interface Radio {
        family: "radio";
        ref: CloudPDF.FormFieldRef;
        name: string;
        origin: FormFieldRadio.Origin;
        readOnly: boolean;
        required: boolean;
        noExport: boolean;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.FormFieldRadioValueEntry;
        defaultValueEntry: CloudPDF.FormFieldRadioDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: FormFieldRadio.Widgets.Item[];
        value: string;
        radiosInUnison: boolean;
        noToggleToOff: boolean;
    }

    export namespace FormFieldRadio {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];
        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.AnnotationRef | null;
                objectNumber: number;
                page: CloudPDF.PageRef | null;
                rect: Item.Rect | null;
                onState: string;
                exportValue: string;
                checked: boolean;
            }

            export namespace Item {
                export interface Rect {
                    x: number;
                    y: number;
                    width: number;
                    height: number;
                }
            }
        }
    }

    export interface Combobox {
        family: "combobox";
        ref: CloudPDF.FormFieldRef;
        name: string;
        origin: FormFieldCombobox.Origin;
        readOnly: boolean;
        required: boolean;
        noExport: boolean;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.FormFieldComboboxValueEntry;
        defaultValueEntry: CloudPDF.FormFieldComboboxDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: FormFieldCombobox.Widgets.Item[];
        value: string;
        defaultValue: string;
        edit: boolean;
        options: FormFieldCombobox.Options.Item[];
    }

    export namespace FormFieldCombobox {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];
        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.AnnotationRef | null;
                objectNumber: number;
                page: CloudPDF.PageRef | null;
                rect: Item.Rect | null;
            }

            export namespace Item {
                export interface Rect {
                    x: number;
                    y: number;
                    width: number;
                    height: number;
                }
            }
        }

        export type Options = Options.Item[];

        export namespace Options {
            export interface Item {
                label: string;
                value: string;
                selected: boolean;
            }
        }
    }

    export interface Listbox {
        family: "listbox";
        ref: CloudPDF.FormFieldRef;
        name: string;
        origin: FormFieldListbox.Origin;
        readOnly: boolean;
        required: boolean;
        noExport: boolean;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.FormFieldListboxValueEntry;
        defaultValueEntry: CloudPDF.FormFieldListboxDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: FormFieldListbox.Widgets.Item[];
        selectedValues: string[];
        defaultValue: string[];
        multiSelect: boolean;
        options: FormFieldListbox.Options.Item[];
    }

    export namespace FormFieldListbox {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];
        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.AnnotationRef | null;
                objectNumber: number;
                page: CloudPDF.PageRef | null;
                rect: Item.Rect | null;
            }

            export namespace Item {
                export interface Rect {
                    x: number;
                    y: number;
                    width: number;
                    height: number;
                }
            }
        }

        export type Options = Options.Item[];

        export namespace Options {
            export interface Item {
                label: string;
                value: string;
                selected: boolean;
            }
        }
    }

    export interface Pushbutton {
        family: "pushbutton";
        ref: CloudPDF.FormFieldRef;
        name: string;
        origin: FormFieldPushbutton.Origin;
        readOnly: boolean;
        required: boolean;
        noExport: boolean;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.FormFieldPushbuttonValueEntry;
        defaultValueEntry: CloudPDF.FormFieldPushbuttonDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: FormFieldPushbutton.Widgets.Item[];
    }

    export namespace FormFieldPushbutton {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];
        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.AnnotationRef | null;
                objectNumber: number;
                page: CloudPDF.PageRef | null;
                rect: Item.Rect | null;
            }

            export namespace Item {
                export interface Rect {
                    x: number;
                    y: number;
                    width: number;
                    height: number;
                }
            }
        }
    }

    export interface Signature {
        family: "signature";
        ref: CloudPDF.FormFieldRef;
        name: string;
        origin: FormFieldSignature.Origin;
        readOnly: boolean;
        required: boolean;
        noExport: boolean;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.FormFieldSignatureValueEntry;
        defaultValueEntry: CloudPDF.FormFieldSignatureDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: FormFieldSignature.Widgets.Item[];
    }

    export namespace FormFieldSignature {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];
        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.AnnotationRef | null;
                objectNumber: number;
                page: CloudPDF.PageRef | null;
                rect: Item.Rect | null;
            }

            export namespace Item {
                export interface Rect {
                    x: number;
                    y: number;
                    width: number;
                    height: number;
                }
            }
        }
    }

    export interface Unknown {
        family: "unknown";
        ref: CloudPDF.FormFieldRef;
        name: string;
        origin: FormFieldUnknown.Origin;
        readOnly: boolean;
        required: boolean;
        noExport: boolean;
        alternateName: string | null;
        mappingName: string | null;
        valueEntry: CloudPDF.FormFieldUnknownValueEntry;
        defaultValueEntry: CloudPDF.FormFieldUnknownDefaultValueEntry;
        actions?: CloudPDF.PdfFieldActions | undefined;
        widgets: FormFieldUnknown.Widgets.Item[];
        rawValue: string;
    }

    export namespace FormFieldUnknown {
        export const Origin = {
            Acroform: "acroform",
            Recovered: "recovered",
        } as const;
        export type Origin = (typeof Origin)[keyof typeof Origin];
        export type Widgets = Widgets.Item[];

        export namespace Widgets {
            export interface Item {
                ref: CloudPDF.AnnotationRef | null;
                objectNumber: number;
                page: CloudPDF.PageRef | null;
                rect: Item.Rect | null;
            }

            export namespace Item {
                export interface Rect {
                    x: number;
                    y: number;
                    width: number;
                    height: number;
                }
            }
        }
    }
}
