// This file was auto-generated by Fern from our API Definition.

export interface MetadataPatch {
    title?: (string | null) | undefined;
    author?: (string | null) | undefined;
    subject?: (string | null) | undefined;
    keywords?: (string | null) | undefined;
    producer?: (string | null) | undefined;
    creator?: (string | null) | undefined;
    createdAt?: (string | null) | undefined;
    modifiedAt?: (string | null) | undefined;
    trapped?: MetadataPatch.Trapped | undefined;
}

export namespace MetadataPatch {
    export const Trapped = {
        True: "true",
        False: "false",
        Unknown: "unknown",
    } as const;
    export type Trapped = (typeof Trapped)[keyof typeof Trapped];
}
