// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type PagePosition =
    | ("start" | "end")
    | {
          before?: CloudPDF.PageRef | undefined;
          after?: CloudPDF.PageRef | undefined;
      };
