// This file was auto-generated by Fern from our API Definition.

import type * as CloudPDF from "../index.js";

export type PdfDestination =
    | CloudPDF.PdfDestination.Xyz
    | CloudPDF.PdfDestination.Fit
    | CloudPDF.PdfDestination.FitH
    | CloudPDF.PdfDestination.FitV
    | CloudPDF.PdfDestination.FitR
    | CloudPDF.PdfDestination.FitB
    | CloudPDF.PdfDestination.FitBh
    | CloudPDF.PdfDestination.FitBv;

export namespace PdfDestination {
    export interface Xyz {
        kind: "xyz";
        page: PdfDestinationXyz.Page;
        left?: (number | null) | undefined;
        top?: (number | null) | undefined;
        zoom?: (number | null) | undefined;
    }

    export namespace PdfDestinationXyz {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface Fit {
        kind: "fit";
        page: PdfDestinationFit.Page;
    }

    export namespace PdfDestinationFit {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface FitH {
        kind: "fitH";
        page: PdfDestinationFitH.Page;
        top?: (number | null) | undefined;
    }

    export namespace PdfDestinationFitH {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface FitV {
        kind: "fitV";
        page: PdfDestinationFitV.Page;
        left?: (number | null) | undefined;
    }

    export namespace PdfDestinationFitV {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface FitR {
        kind: "fitR";
        page: PdfDestinationFitR.Page;
        left: number;
        bottom: number;
        right: number;
        top: number;
    }

    export namespace PdfDestinationFitR {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface FitB {
        kind: "fitB";
        page: PdfDestinationFitB.Page;
    }

    export namespace PdfDestinationFitB {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface FitBh {
        kind: "fitBH";
        page: PdfDestinationFitBh.Page;
        top?: (number | null) | undefined;
    }

    export namespace PdfDestinationFitBh {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export interface FitBv {
        kind: "fitBV";
        page: PdfDestinationFitBv.Page;
        left?: (number | null) | undefined;
    }

    export namespace PdfDestinationFitBv {
        export interface Page {
            kind: Page.Kind;
            pageObjectNumber: number;
        }

        export namespace Page {
            export const Kind = {
                ObjectNumber: "objectNumber",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }
}
